### ISSUE TITLE
[BUG] using midi console-tool leads to leaked mmcss-threads (eg on midi endpoint ... send-message ...)

### ISSUE THREAD

**Issue by JanneRoeper** [microsoft/MIDI#120]
**Applies To**
Developer Preview 1.1

**Describe the bug**
When counting system-wide threads with priority equal or greater than 20 I noticed when testing with midi console-tool, additional threads (with priority 25) appear after specific commands have been finished, like "midi endpoint ... send-message ... " or "midi endpoint ... monitor (after having pressed Escape)". They sum up over time and may hit the system-wide 128-mmcss-thread limit, I guess. Stopping the MIDI Service cleans-up all those additional threads. After (re-)starting the MIDI Service the number is back to the beginning.

**To Reproduce**
1. Use a tool to count the system-wide threads with priority above or equal 20
2. call midi console-tool functions like: "midi endpoint ... send-message ... " or "midi endpoint ... monitor"
3. Count the threads again: you'll notice a steady increase

**Expected behavior**
No leaked mmcss-threads.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Build 19045.3448

**Do you wish to contribute a fix for this problem?**

**Additional context**

**Comment by Psychlist1972** [comment]
Thanks. Eventually this will be a non-issue as process shutdown (of any sort) will close the service connection which has the allocated MMCSS thread. However, it's a good practice to close what you open, so I have that in my branch. I'll update this when I PR to main.
