### ISSUE TITLE
missing package

### ISSUE THREAD

**Issue by technical-publishing** [microsoft/MIDI#162]
Hello, 
I don´t know if this is the right place for my post, but I can´t find a better one. I want to compile the MIDI Service console but I got the message that the package:

Windows.Devices.MIDI2

was not found. How can I add it to my project?

Thanks a lot and best regards,
Werner

**Comment by Psychlist1972** [comment]
Hi Werner

You could also ask questions like this on our Discord server. Link is in the main readme for this repo.

Windows.Devices.Midi2 winmd / nuget package is built as part of the full Windows MIDI Services here. It's also dependent upon the Windows service, and the transport and transform plugins. The Windows.Devices.Midi2 types also need special registration which, for *developer preview use only* our setup packages take care of.

This will ship with Windows starting in 2024. The MIDI Console is not useful without all of those parts (API, service, components, registration entries, config files, etc.).

I'll post the latest interim build here on Github soon so you don't have to build everything yourself if you don't want to. I have to move the location of the message scheduling logic, which is taking a bit longer than expected.

Pete

**Comment by technical-publishing** [comment]
Hi Pete,

thanks a lot for your answer and sorry for the long delay, but I was ill for a few days. I have created a discord account and I will follow all developments there.

Best regards,
Werner

**Comment by Psychlist1972** [comment]
In case you missed it, I put out a release with all the packages (actually two releases) so you should be able to compile the console if you want to. The installer also installs the console and puts it in the path, FYI.
