### ISSUE TITLE
[BUG] Endian translation on Group Terminal Blocks not correct for bandwidth values

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#163]
**Applies To**
USB MIDI 2.0 Driver

**Describe the bug**
Max output bandwidth was translated incorrectly. Not getting the correct values

(No screenshots due to confidentiality of device)

**Comment by AmeNote-Michael** [comment]
@Psychlist1972 after further investigation, it is determined that the driver mapping values for maxInputBandwidth and maxOutputBandwidth in Group Terminal Blocks is correct. Issue is actually with test application we have been using to check against.

Therefore there is no change required.
