### ISSUE TITLE
[BUG] Multiple UMP Messages in single USB Packet

### ISSUE THREAD

**Issue by AmeNote-Michael** [microsoft/MIDI#165]
**Applies To**
USB Driver or Service

**Describe the bug**
Transmission of multiple UMP messages in a single USB Packet is not being properly handled by system. Messages are dropped.

**To Reproduce**
Using a USB MIDI 2.0 device like ProtoZOA, connect and send in single USB packet a set of UMP messages like:
40 91 23 45 67 89 00 00
40 91 23 45 67 89 00 01
40 91 23 45 67 89 00 02
40 91 23 45 67 89 00 03

Using midi.exe console application, observe that not all messages received through system by Windows.
midi endpoint monitor --verbose

Note this issue was reported originally by AMEI (Yamaha: Daisuke Miura).
Supplied by AMEI, attached .uf2 file loads onto ProtoZOA UUT to reproduce issue.

**Expected behavior**
All 4 messages sent should be observed in the console application.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 (Canary)
[multiump.uf2.zip](https://github.com/microsoft/MIDI/files/13691287/multiump.uf2.zip)

**Comment by AmeNote-Michael** [comment]
@dmiura testing with @Psychlist1972 latest developer release and driver - [Developer Preview 3](https://github.com/microsoft/MIDI/releases/tag/dev-preview-3) I have not been able to reproduce issue. It is possible that something in queuing or displaying causes the issue.

Even with latest preview, the buffer falls behind on midi endpoint monitor --verbose such that after unplugging the test device from USB, it took some time before the display scrolling stops.

Can you please try again and confirm issue with latest developer preview.

**Comment by Psychlist1972** [comment]
@AmeNote-Michael

Multiple UMP messages in a single transfer *to or from the service* are not supported, especially not at the API level. Did Gary do something special with the USB interface to pull apart the messages and support this scenario for the USB driver?

There are a number of checks in various places to ensure we're dealing with a single message at a time.

**Comment by Psychlist1972** [comment]
@AmeNote-Michael  also getting reports related to this from others. I've asked folks to comment here.

**Comment by m-komo** [comment]
@AmeNote-Michael 
I've run the following command on the ProtoZOA.

> midi.exe send-message 0x41234567 0x00000000 --count 10000 --pause 0 --debug-auto-increment

Since there is no message interval, the MIDI Service finishes sending messages instantly.
However, it seems that the driver only sends one UMP per transaction.
It is expected that the driver sends multiple UMPs per transaction (URB) to get better performance if there are several UMPs in the buffer sent from the service.

![ProtoZOA-send_message_zero_interval](https://github.com/microsoft/MIDI/assets/114042371/c2ad7c75-66e1-494e-add6-34ae40eaf113)

- OS: Windows 11 Version 23H2 (build 26020.1000)
- MIDI Service: DP4 Dairy 3 (1.0.24018.1850)
- Driver: USBMidi2 Ver.10.0.1.3 (included in DP2)

**Comment by AmeNote-Michael** [comment]
@m-komo I pass the UMP data to the USB device as I receive them from the service. I will discuss with team how we can look to group messages better.

**Comment by AmeNote-Michael** [comment]
@dmiura I looked closely at code and it appears that the driver is properly capturing the 4 packets and passing up to service. Will need to investigate further with rest of team.

**Comment by AmeNote-Michael** [comment]
@dmiura I investigated further on weekend. I believe I have figured out mechanism on why USB Out is sending only one UMP per USB packet. Essentially I have no policy on number USB packets queued to send, as long as USB stack accepts a packet to send, I create and send it.

With no limit, driver could submit hundreds if not thousands of single UMP packet messages to USB to send to device.

Driver will be updated to limit the number of USB send packets to device which should force to group UMP messages.

**Comment by m-komo** [comment]
@AmeNote-Michael Any update on the DP5 driver?
It seems that the driver still sends one UMP per transaction.

**Comment by AmeNote-Michael** [comment]
This issue was resolved and fixed.

**Comment by m-komo** [comment]
I have confirmed that the issue was resolved.
- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/19/2024,23.22.46.475)
- OS: Windows 11 24H2 (OS Build 26100.1150)
