### ISSUE TITLE
[BUG] Known issue: USB MIDI driver supports only a single device at a time.

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#166]
The USB MIDI 2.0 driver currently supports using only a single USB device at a time. This is a known developer preview issue, but documenting it here.

**Comment by Psychlist1972** [comment]
One symptom of this is the way midi.exe displays the data.

If you connect and monitor two devices, they will both enumerate and will *appear* to work at first

Monitor the first one: all good
Monitor the second one at the same time, and you may see a message appear in the output of the first one before things go unstable and possibly lock up. In my case, I have to control-C the midi.exe client, which does not shut down the service connection properly.

If anyone else finds themselves in this situation, after closing your app or the midi.exe console, go into the service control panel (Search->"Services") and restart the `Microsoft MIDI Service`

**Comment by AmeNote-Michael** [comment]
Resolved, to be verified. Pull request https://github.com/microsoft/MIDI/pull/278

**Comment by Psychlist1972** [comment]
This is in Developer Preview 5
