### ISSUE TITLE
[BUG] Many scheduled messages dropped

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#174]
**Describe the bug**
Giel Bremmers reported that he was seeing a regression where some scheduled messages were being dropped. 

**To Reproduce**

I was able to reproduce this with the console

`midi endpoint send-message 0x21234567 --count 100 -o 2000000`

In my case, only 26 messages were received. I restarted the service and ran the test again, and only 25 messages were received.

Note that sending smaller numbers of messages (like 10) doesn't repro the problem.

**Comment by dmiura** [comment]
**Describe the bug**
Same issue we found. 

**To Reproduce**
We are using ProtoZOA with following firmware.
https://github.com/midi-mma/Amenote_Protozoa/blob/main/Releases/V0.4/ProtoZOA_Main.uf2
[ZoA_UUT.uf2.zip](https://github.com/microsoft/MIDI/files/13734003/ZoA_UUT.uf2.zip)
When "5" button on ProtoZOA, it will send UMP message(Note On) with 500usec interval, "3" means 300usec.

When ProtoZOA sends continuously UMP MIDI 2.0 Note On messages with interval e.g. 500usec, then it seems that some scheduled messages were being dropped, around 100,000 messages.

**Comment by Psychlist1972** [comment]
Thanks. Currently working on this issue.

**Comment by Psychlist1972** [comment]
@dmiura

> **To Reproduce** We are using ProtoZOA with following firmware. https://github.com/midi-mma/Amenote_Protozoa/blob/main/Releases/V0.4/ProtoZOA_Main.uf2 [ZoA_UUT.uf2.zip](https://github.com/microsoft/MIDI/files/13734003/ZoA_UUT.uf2.zip) When "5" button on ProtoZOA, it will send UMP message(Note On) with 500usec interval, "3" means 300usec.
> 
> When ProtoZOA sends continuously UMP MIDI 2.0 Note On messages with interval e.g. 500usec, then it seems that some scheduled messages were being dropped, around 100,000 messages.

There's a thread on Discord about this issue as well. I put together an interim build tonight to test. If you want to try it out, please do. There's some additional context in that thread as well.

https://discord.com/channels/980245825202552942/1186980629829664818/1187293982812807199
