### ISSUE TITLE
[BUG] Some parent USB Device properties aren't correct

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#186]
**Applies To**
New USB MIDI 2.0 Class Driver / Windows USB Stack

**Describe the bug**
Certain properties of the **parent device** are not correct. The value of some of them makes me think the driver is responsible for at least some of the data. This is pre-enumeration from the service, so completely in the realm of driver and USB stack.

Examples:
System.Devices.DeviceManufacturer is set to "USBMidi2" instead of the actual device manufacturer from the USB device.
System.Devices.ModelName is set to null

**To Repro**

Use the MIDI Console and issue `midi endpoint properties --verbose` and look at the "Parent Device" section.

You can also see the values using pnputil

`pnputil /enum-devices /instanceid "<device instance id>" /properties`

In my case, there are some key values that pnputil is reporting:

```
    DEVPKEY_Device_DeviceDesc [String]:
        USBMidi2-ACX
    DEVPKEY_Device_DriverVersion [String]:
        10.0.1.3
    DEVPKEY_Device_DriverDesc [String]:
        USBMidi2-ACX
    DEVPKEY_Device_DriverInfPath [String]:
        oem119.inf
    DEVPKEY_Device_DriverInfSection [String]:
        USBMidi2Device
    DEVPKEY_Device_MatchingDeviceId [String]:
        usb\vid_cafe&pid_4001&mi_02
    DEVPKEY_Device_DriverProvider [String]:
        USBMidi2
 DEVPKEY_Device_Manufacturer [String]:
        USBMidi2
```

**Comment by AmeNote-Michael** [comment]
@garydan42 these parameters are not populated by me. Unless I can override them, we may need to create our own parameters for the expected values. Is this correct?

**Comment by Psychlist1972** [comment]
Closing this because recent check-ins provide the manufacturer name as a property we capture directly.
