### ISSUE TITLE
[BUG] MIDI Console app will not ESC on midi endpoint monitor if heavy data streaming

### ISSUE THREAD

**Issue by AmeNote-Michael** [microsoft/MIDI#200]
**Applies To**
midi console application

**Describe the bug**
When monitoring a USB device that is streaming constant data, the console app does not seem to notice the esc button pressed until data stops flowing, eg. unplug of USB device and waiting for buffer display to catch up.

Although this is not normal operation, just noted that can occur. We are talking about 4 UMP MIDI 2.0 messages sent in USB packet back to back, so lots of data.

**To Reproduce**
On ProtoZOA, use load in Issue https://github.com/microsoft/MIDI/issues/165 which will send the back to back UMP data.

**Expected behavior**
Should be able to esc from the midi endpoint monitor at any time regardless of amount of data streaming. Otherwise need to wait until all buffers are clear to eventually esc out of program.

**Comment by Psychlist1972** [comment]
Fixed in main.
