### ISSUE TITLE
[BUG] Built-in loopback endpoints should not have captured metadata

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#205]
The built-in loopback endpoints should not capture metadata like endpoint name, function blocks, and more because this will persist.

Or, if we decide it's a good idea to allow this for testing, then restarting the service should clear all metadata for the loopback ports.

**Comment by Bremmers** [comment]
I think being able to define FBs for the loopbacks is very useful for testing. Our tests do this.

The data certainly should be reset when the service starts. Perhaps even something like MidiEndpointDeviceInformation.ResetLoopEndpoints() would be convenient. You could write this yourself if need be, of course.

**Comment by Psychlist1972** [comment]
We'll keep the metadata capture here, but clear it whenever the service is restarted.

**Comment by Psychlist1972** [comment]
Done
