### ISSUE TITLE
[Feature] Make x-proc buffer sizes configurable

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#219]
Recommend pulling the buffer sizes from the registry. Currently, they all default to 0x1000 which is PAGE_SIZE.

If a global setting, I recommend
```
\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows MIDI Services
DWORD ClientBufferSizeBytes
```

If a per-transport setting, I recommend
```
\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows MIDI Services\Transport Plugins\<Plugin Name>\
DWORD ClientBufferSizeBytes
```

If a per-device setting, it could come from the configuration file loaded by MidiSrv, but that requires plumbing it through

If a per client connection setting, you may want to add it to `ABSTRACTIONCREATIONPARAMS` and have it passed up from the API?

Would be good to do the same for device side if it's different. If Client and Device will be the same, I recommend changing above values to `BufferSizeInBytes` and use for both.

**Comment by Psychlist1972** [comment]
Related source: `CMidi2MidiSrv::Initialize`

**Comment by Paul-Dempsey** [comment]
Hopefully these registry settings and API settings are range-checked for sanity, otherwise looks like an attack vector.

**Comment by Psychlist1972** [comment]
> Hopefully these registry settings and API settings are range-checked for sanity, otherwise looks like an attack vector.

Yeah. perhaps a min of  256 and a max of PAGE_SIZE * 16 (65,536) or something. 64k is huge, but not going to bring down the system, and could be appropriate for devices doing OS firmware updates using Flex Data messages. Regardless, the different values would need to be tested.

**Comment by Psychlist1972** [comment]
Decided against this for now.
