### ISSUE TITLE
[BUG] Receiving Channel Pressure via USB MIDI 1 doesn't work in Preview 3 and 4

### ISSUE THREAD

**Issue by JanneRoeper** [microsoft/MIDI#225]
**Applies To**
see title

**Describe the bug**
see title
It works when using Loopback A/B

**To Reproduce**
Connect a USB MIDI 1 device that is able to send Channel Pressure
Monitor the port, you won't receive anything. Other messages work (PitchBend, NoteOn/Off, ControlChange).

**Expected behavior**
Should work :-)

**Screenshots**
None

**Installer Name or Version**
Preview 3 and 4

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - OS Build from Settings > System > About: 19045.3930

**Do you wish to contribute a fix for this problem?**
No

**Additional context**

**Comment by Psychlist1972** [comment]
@JanneRoeper is the USB MIDI 1.0 device using the new driver or a different USB driver?

**Comment by Psychlist1972** [comment]
> I didn't install any new driver here as it was said that the new one only works with Windows 11.

Correct. I missed that this was in Windows 10. So this is likely part of the translation code in the service.

**Comment by m-komo** [comment]
In the case of Channel Pressure with MIDI channel 1 seems to work fine.

Following shows a result of loopback test on an USB MIDI 1.0 device (Roland UM-ONE).
![image](https://github.com/microsoft/MIDI/assets/114042371/e8ceb1d6-01d1-4dff-bdc5-f5ecba60110c)

All messages are sent and received on USB.
![image](https://github.com/microsoft/MIDI/assets/114042371/ab987b6a-2264-4470-aee8-74ba61e7437a)

**Comment by m-komo** [comment]
The issue persists on the DP5.
- MIDI Service version: DP5 (1.0.24066.2126)
- Driver version: DP5 (10.0.14)
- OS version: Windows 11 24H2 build 26063.1

**Comment by m-komo** [comment]
I have confirmed that the issue has been solved.
- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
- OS: Windows 11 24H2 (OS Build 26100.1150)
