### ISSUE TITLE
[BUG] Receiving SysEx via USB MIDI 1 doesn't work in Preview 3 and 4

### ISSUE THREAD

**Issue by JanneRoeper** [microsoft/MIDI#226]
**Applies To**
see title

**Describe the bug**
see title
It works when sending & receiving via Loopback A/B

**To Reproduce**
Connect a USB MIDI 1 device and let it send SysEx (in my case with 9 bytes payload excluding F0 & F7). Use midi.exe to monitor the port. You'll only see SysEx7 Start Messages. The rest is missing.

**Expected behavior**
Should work

**Screenshots**
Some recorded traffic beyond what is decribed above:
![grafik](https://github.com/microsoft/MIDI/assets/124163/c45956e7-b578-4e74-bdd6-677c9384bd56)

**Installer Name or Version**
Preview 3 & 4

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - OS Build from Settings > System > About: 19045.3930

**Do you wish to contribute a fix for this problem?**
No

**Additional context**
None

**Comment by Psychlist1972** [comment]
Just a note that this is on Windows 10 with an existing driver, not the new USB MIDI 2.0 driver.
