### ISSUE TITLE
[BUG] Dropped messages when large numbers of messages sent as fast as possible

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#227]
**Applies To**
Service or console

**Describe the bug**

**To Reproduce**
open midi.exe in two windows
from one, monitor loopback B
from the other `midi endpoint send-message 0x41234567 0x00000000 --count 10000 --pause 0 --debug-auto-increment`

First time around, all messages are received.
Second time around, 3-5 messages end up dropped. (not sure where in the stream they are dropped, but it seems possible it's at the end.
These messages are not received by the midi client, so it is not simply a display problem.

This was reproduced even after increasing the client buffer sizes from `PAGE_SIZE` to `PAGE_SIZE * 4`

**Additional context**

Forked from issue #182

**Comment by Psychlist1972** [comment]
When messages are sent with a delay (currently, any delay over 0, as the minimum for the thread sleep is around 15ms) there are no dropped messages.

But if sent as quickly as possible, there are dropped messages. I've added a couple of debug parameters to the console to be able to see this type of things. The first is an optional auto-increment on the send-message. The second is to allow the monitor to detect debug messages that are skipped.

With that, I could confirm that the messages are being skipped in-line, not at the end or beginning.

![image](https://github.com/microsoft/MIDI/assets/1421146/81ad6810-e118-4f94-86b0-60e9be584f0e)

![image](https://github.com/microsoft/MIDI/assets/1421146/0dcdd630-9615-43eb-be74-975fb8a41d26)

(ignore the processing / receive time in that last screenshot. It doesn't look correct)

**Comment by Psychlist1972** [comment]
For 1,000,000 messages sent as quickly as possible.

![image](https://github.com/microsoft/MIDI/assets/1421146/094d72fd-482f-41be-9506-a3c4ded118f6)

**Comment by dmiura** [comment]
@Psychlist1972
This is just a quick report.
We've been also checking #182 issue on DP4 Daily-3
It seems that Daily-3 improved than Daily-2, but not perfect.
The following chart is number of dropped messages with several durations.
It's no problem 400usec duration but dropped messages occurred in shorter duration.
Duration(sec) | Daily-2 | Daily-3
-- | -- | --
100u | 45 | 30
200u | 30 | 3
300u | 4 | 0

We will check again and report if we found additional points.

**Comment by dmiura** [comment]
Please find attached ProtoZOA's firmware used in our checking.
[ZoA_UUT100.uf2.zip](https://github.com/microsoft/MIDI/files/14003871/ZoA_UUT100.uf2.zip)

**Comment by Psychlist1972** [comment]
@dmiura thank you. I was not able to repro that here, but will try some more iterations and larger amounts of data.

**Comment by m-komo** [comment]
@Psychlist1972 @dmiura 
I was able to reproduce the issue on the ProtoZOA with 100 usec interval.
#I accidentally closed the console window, so there is no screenshot. Sorry.

However, in the case of using loopback endpoint, I haven't faced this issue even I sent 10 million of messages.

I am wondering which layer can cause this problem...

**Comment by Psychlist1972** [comment]
I was able to reproduce this now with the ProtoZOA at the 100ms interval, only on the third run. (the average is correct only because I didn't do these quite back to back. I'll need to change that to be a different calculation for it to be useful)

![image](https://github.com/microsoft/MIDI/assets/1421146/1385092e-d728-458f-b22d-6e1b04633a82)

**Comment by dmiura** [comment]
@Psychlist1972 @m-komo
We found a bug in ProtoZOA firmware side, please find attached new firmware.
[ZoA_UUT100.uf2.zip](https://github.com/microsoft/MIDI/files/14018615/ZoA_UUT100.uf2.zip)
It was not enough care for wring UMP Packet.
Then, there are no dropped messages.

**Comment by dmiura** [comment]
@Psychlist1972
We fixed additional issue in ProtoZOA firmware.
[ZoA_UUT100.uf2.zip](https://github.com/microsoft/MIDI/files/14074186/ZoA_UUT100.uf2.zip)

Yamaha checked it and Komorita-san also checked it worked fine.

**Comment by Psychlist1972** [comment]
> @Psychlist1972 We fixed additional issue in ProtoZOA firmware. [ZoA_UUT100.uf2.zip](https://github.com/microsoft/MIDI/files/14074186/ZoA_UUT100.uf2.zip)
> 
> Yamaha checked it and Komorita-san also checked it worked fine.

I'm good to close this issue, then?
