### ISSUE TITLE
[BUG] Cannot open a same port from a Win32 app and midi.exe

### ISSUE THREAD

**Issue by tkmymzk-ymh** [microsoft/MIDI#229]
**Describe the bug**
When using both a Win32 app and midi.exe, it is not possible to open the same port simultaneously.

**To Reproduce**
1. Connect a MIDI 1.0 keyboard (such as KORG nanoKEY2) to your PC.
2. Start midi.exe. midi.exe will recognize the MIDI port and receive MIDI messages from the keyboard.
3. Start another Win32 App (such as Pocket MIDI, https://apps.microsoft.com/detail/9NTV7MFLBBVX).
4. Select the same port on Pocket MIDI.
5. A message “Port opened failed” will be displayed.

A similar error occurs when you start Pocket MIDI first.

**Expected behavior**
Both apps using different API should be able to open the same port at the same time.

**Screenshots**
None

**Installer Name or Version**
Preview 4 Daily 2

**Additional context**
This issue may be related to the comment about multi-client support in the API Backward Compatibility section of the README, which states "It is possible we will add multi-client support here after our initial release."

**Comment by Psychlist1972** [comment]
Thanks for the report. This is a known limitation until we re-plumb the older APIs to use Windows MIDI Services. (It's on the backlog). Until that time, the only way to have multi-client is for all apps to use the new API.

Multi-client is implemented at the service level. The older WinMM and WinRT MIDI 1.0 APIs go straight to the driver.

Issue #34

**Comment by tkmymzk-ymh** [comment]
@Psychlist1972  Understood. Thank you for the information!

**Comment by Psychlist1972** [comment]
Related to #49

**Comment by Psychlist1972** [comment]
Closed with release of DP7, with caveats about current WinMM partial implementation (only Group 0, and you must use the midisrv-enumerated ports)
