### ISSUE TITLE
[BUG] 'send-message-file' command is slow.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#233]
**Describe the bug**
I run the following command on the loopback endpoint A and monitored the loopback endpoint B.

`midi endpoint send-message-file Test_ChMsg.txt --pause 0`

I have attached the file used for this test([Test_ChMsg.txt](https://github.com/microsoft/MIDI/files/14007734/Test_ChMsg.txt)).
It contains about 15,000 MIDI 2.0 channel voice messages.

Since the '--pause 0' option was used, all messages are expected to be sent instantly.
However, it took about one hour to complete sending all messages.

**To Reproduce**
Run the following command on the loopback endpoint with the attached "Test_ChMsg.txt".
`midi endpoint send-message-file Test_ChMsg.txt --pause 0`

**Expected behavior**

**Screenshots**
At first, the message interval is not bad, but it takes 2-3 msec even with '--pause 0' option.
![image](https://github.com/microsoft/MIDI/assets/114042371/6d5081dd-4187-40a6-9298-0391b4588ac2)

Then the interval is getting longer and longer and at the end, it will be about 500 msec.
As a result, it takes an hour to complete sending all messages.
![image](https://github.com/microsoft/MIDI/assets/114042371/c452cf81-45be-4612-9640-f5535a006f2d)

If I send 15,000 messages with the 'send-messge' command like below, it takes only 100 msec.
![image](https://github.com/microsoft/MIDI/assets/114042371/58c65f49-b369-43d2-96bf-525649b14af5)

**Installer Name or Version**
- DP4 Daily3 (Windows.MIDI.Services.Developer.Preview.4.x64.1.0.24018.1850.exe)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 build 26020.1000

**Device information, if this is with an external MIDI device:**
 - Diagnostics Loopback endpoint.

**Application Information**
- midi.exe console app.

**Comment by Psychlist1972** [comment]
Thank you for this detailed test and results @m-komo!

**Comment by Psychlist1972** [comment]
Thanks. I see what is happening here. This is using the older table display code. I hadn't yet updated it to use what I created for endpoint monitoring. I will add this to my backlog to bring it up to performance with regular send-message code.

**Comment by Psychlist1972** [comment]
Fixed in the official DP4
