### ISSUE TITLE
[BUG] Receiving Program Change via USB MIDI 1.0 device doesn't work.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#234]
**Describe the bug**
Program Change messages could not be received via USB MIDI 1.0 device which work with an existing USB MIDI 1.0 driver (USBAUDIO.sys).

**To Reproduce**
1. Set the Roland UM-ONE to class compliant mode and short UM-ONE's INPUT and OUTPUT to loop back the message. 
2. Attach UM-ONE to the PC and make sure the device is working with USBAUDIO.sys.
3. Open midi.exe in two windows.
4. From one, monitor UM-ONE.
5. From the other, run following command with attached file:
`midi endpoint send-message-file Test_ProgramChange.txt`

**Expected behavior**
All sent MIDI 1.0 Program Change messages are received.

**Observed behavior**
Only a message with the MIDI channel 1 was received.

![image](https://github.com/microsoft/MIDI/assets/114042371/278c41f4-df01-48d2-b699-4a3948431090)

**Screenshots**
All messages are sent and received on the USB transaction.

![image](https://github.com/microsoft/MIDI/assets/114042371/61f58f3d-12a0-4452-b934-162b1fde90cf)

**Installer Name or Version**
- DP4 Daily3 (Windows.MIDI.Services.Developer.Preview.4.x64.1.0.24018.1850.exe)

**Desktop (please complete the following information):**
- OS: Windows 11 23H2 build 26020.1000

**Device information, if this is with an external MIDI device:**
- Roland UM-ONE mk2
- Classic MIDI 1.0 class driver (USBAUDIO.sys)

**Application Information**
- midi.exe console app.

**Comment by m-komo** [comment]
If the device is working with the new USB MIDI 2.0 driver (USBMidi2.sys), all messages are received.
![image](https://github.com/microsoft/MIDI/assets/114042371/92877e0a-639b-4a17-8ad9-1c36a5cee342)

**Comment by Psychlist1972** [comment]
This should be fixed as soon as we pull in the new AM Lib from Andrew. We're working on the vcxpkg approach to be able to properly consume that.

**Comment by m-komo** [comment]
The issue persists on the DP5.
- MIDI Service version: DP5 (1.0.24066.2126)
- Driver version: DP5 (10.0.14)
- OS version: Windows 11 24H2 build 26063.1

**Comment by m-komo** [comment]
I have confirmed that the issue has been solved.
- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
- OS: Windows 11 24H2 (OS Build 26100.1150)
