### ISSUE TITLE
[BUG] MidiSrv.exe crashes

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#240]
**Describe the bug**
When running midi.exe on the USB MIDI 1.0 device which is working with the Windows in-box USB MIDI driver (USBAUDIO.sys), MidiSrv crashes suddenly.

I have attached several event log files.
[EventLogFiles.zip](https://github.com/microsoft/MIDI/files/14096345/EventLogFiles.zip)

**To Reproduce**
1. Set the Roland UM-ONE mk2 to class-compliant mode.
2. Attach the device to PC.
3. Open the Device Manager and make sure the device is working with the Windows in-box USB MIDI driver (USBAUDIO.sys).
4. Open midi.exe in two windows.
5. From one, monitor UM-ONE.
6. From the other, run following command with attached file:
'midi endpoint send-message-file TestAllMTs.txt'

After completing to end messages, MidiSrv crashes.

**Expected behavior**
MidiSrv never crashes.

**Installer Name or Version**
Windows.MIDI.Services.Developer.Preview.4.x64.1.0.24022.2031.exe

**Desktop (please complete the following information):**
- OS: Windows 11 23H2 build **26040.1000**

**Device information, if this is with an external MIDI device:**
- Roland UM-ONE mk2

- Classic MIDI 1.0 class driver (USBAUDIO.sys)

**Application Information**
- midi.exe console app.

**Comment by AmeNote-Michael** [comment]
Please retest with next driver version that had pull request https://github.com/microsoft/MIDI/pull/301

**Comment by Psychlist1972** [comment]
> Please retest with next driver version that had pull request #301

This is with our older class driver, so not MIDI 2.0 driver

**Comment by sat-okada** [comment]
I have confirmed that this issue is resolved with the latest version of the driver (23.1.50.504) and dp6.

**Comment by m-komo** [comment]
I have confirmed that the issue has been solved.
- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
- OS: Windows 11 24H2 (OS Build 26100.1150)

**Comment by m-komo** [comment]
It seems I haven't attached [TestAllMTs.txt](https://github.com/user-attachments/files/16278256/TestAllMTs.txt) to verify this issue. Sorry.

**Comment by m-komo** [comment]
The issue was resolved.
