### ISSUE TITLE
[TODO] Implement option to not use MMCSS threads when creating a new session (or just remove use of MMCSS threads)

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#285]
MMCSS threads are a finite resource in any process. Right now, the MIDI client uses one MMCSS thread per incoming stream, causing some applications to run out of threads.

If MMCSS provides a desirable performance boost, provide an option to not use MMCSS threads. If the performance difference is negligible, then move to regular high priority threads.

**Comment by JanneRoeper** [comment]
That would be really appreciated! Thanks!
Keep in mind that using MMCSS threads does limit the number of connectable MIDI endpoints to 32 minus other-MMCSS-threads-running-in-the-process, also.

**Comment by Psychlist1972** [comment]
@JanneRoeper 

Yep, and that is a concern. We're investigating whether we really need MMCSS for this at all. It does help reduce jitter, but it may not be enough to be concerned with. In the release coming this week, MMCSS is still enabled.

**Comment by Psychlist1972** [comment]
@JanneRoeper The next dev preview has MMCSS threads removed from the service and abstraction through a conditional compile. We'll see if that performs well enough for everyone.

**Comment by Psychlist1972** [comment]
Actually, I've made this a registry setting now.

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows MIDI Services\UseMMCSS (DWORD). 0 is off, > 0 is on.

**Comment by Psychlist1972** [comment]
By default,, MMCSS for MidiSrv is off. Changing this requires the MIDI Service to be restarted

So far, we've seen minimal performance impact with MMCSS turned off for MIDI, but we are continuing to test with different machines/configs/etc.

The key may even be locked down with the rest of that part of the hive so that no one can change it. Turning on MMCSS gives you a little performance boost, but only if the application doesn't need the MMCSS threads itself, and only if there are a small number of MIDI devices connected where the number of created input queues for a device (including winmm backwards compat client queues) is below the number of available threads.

**Comment by JanneRoeper** [comment]
This sounds perfect to me! Thanks!

**Comment by Psychlist1972** [comment]
(and yes, this is a DP7 change, not in DP6)

**Comment by Psychlist1972** [comment]
Closed with release of DP7
