### ISSUE TITLE
[BUG] USB MIDI 2 Driver returns incorrect size for iSerialNumber property

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#286]
**Describe the bug**
The code to return the `iSerialNumber` returns an incorrect length (sizeof(GUID) instead of length+1 * sizeof(WCHAR)) which causes a service crash. 

Service code to retrieve the `iSerialNumber` has been commented out until this is fixed.

Feb 2024 attestation driver

**Comment by AmeNote-Michael** [comment]
Bug in code returning incorrect parameter for size. Resolved in pull request #301

**Comment by Psychlist1972** [comment]
Reopening until we ship to customers
