### ISSUE TITLE
[BUG] Return manufacturer name from ACX driver

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#288]
**Describe the bug**

Current driver impl doesn't yet return device manufacturer name from the `iManufacturer` string in the device descriptors.

**Comment by AmeNote-Michael** [comment]
Added with KSPROPERTY of:

KSPROPERTY_MIDI2_DEVICE_MANUFACTURER

**Comment by Psychlist1972** [comment]
> Added with KSPROPERTY of:
> 
> KSPROPERTY_MIDI2_DEVICE_MANUFACTURER

@AmeNote-Michael 

As with VID/PID, these were there already

https://github.com/microsoft/MIDI/blob/main/src/api/Inc/MidiKSDef.h

**Comment by AmeNote-Michael** [comment]
Feature missed during a merge. Readded and in pull request #301

**Comment by Psychlist1972** [comment]
Reopening until we ship to customers

**Comment by Psychlist1972** [comment]
This is fixed in the August 2024 driver release. However, it will require DP7 for folks to see the name in the SDK or midi console.

**Comment by AmeNote-Michael** [comment]
@Psychlist1972 can this issue be closed?
