### ISSUE TITLE
[Feature] Add VID and PID as data requests to driver

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#289]
Following the same request pattern as serial number, it would be helpful for the driver to return the VID and PID, separate fields, so that we can easily include them in search criteria for device matching when it is moved from USB port to USB port.

We can set up VID as the next item in the DDI enumeration and PID as the one after that.

![image](https://github.com/microsoft/MIDI/assets/1421146/4ad9890d-1c31-41ae-807e-b257ef5a8b94)

Both are USHORT values.

**Comment by AmeNote-Michael** [comment]
@garydan42 please add following properties:
    KSPROPERTY_MIDI2_DEVICE_VID,
    KSPROPERTY_MIDI2_DEVICE_PID,

**Comment by Psychlist1972** [comment]
> @garydan42 please add following properties: KSPROPERTY_MIDI2_DEVICE_VID, KSPROPERTY_MIDI2_DEVICE_PID,

@AmeNote-Michael 

Those are there already, as in the above screenshot. I added them :)

https://github.com/microsoft/MIDI/blob/main/src/api/Inc/MidiKSDef.h

**Comment by AmeNote-Michael** [comment]
Feature added in pull request #301
