### ISSUE TITLE
[BUG] Cannot build C++ code against preview 5 source package

### ISSUE THREAD

**Issue by jcelerier** [microsoft/MIDI#296]
**Describe the bug**
Cannot build with current source package (preview 5)

**To Reproduce**
- Download https://github.com/microsoft/MIDI/releases/download/dev-preview-5/Windows.Devices.Midi2.zip
- Include Windows.Devices.Midi2.h in a .cpp file and add the relevant path
- Build failure:
```
winmidi-src\winrt\impl\Windows.Devices.Midi2.2.h(9,10): error C1083: Cannot open include file: 'winrt/impl/Windows.Devices.Midi2.1.h': No such file or directory
```

I indeed don't see such a file anywhere in the archive or in my hard drive.

**Expected behavior**
Build works

I would recommend having a GH action that builds the examples through for instance CMake or direct calls to cl.exe to make sure everything is useable from the C++ ecosystem. In particular without any nuget or IDL generation involved.

**Installer Name or Version**
https://github.com/microsoft/MIDI/releases/download/dev-preview-5/Windows.Devices.Midi2.zip

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Psychlist1972** [comment]
Good catch, thanks. Sorry about that.

The (latest from NuGet) `cppwinrt.exe` tool generates these when you reference a winmd in Visual Studio or from the command-line. I missed including some of them this time around.

Updated the release with a zip file containing the additional headers. `Windows.Devices.Midi2-Updated.zip`

Agreed on cmake. It's on my list, but I have zero experience with it.

**Comment by Psychlist1972** [comment]
[Windows.Devices.Midi2-Updated.zip](https://github.com/microsoft/MIDI/files/14552122/Windows.Devices.Midi2-Updated.zip)

**Comment by Psychlist1972** [comment]
Crap. One sec.

**Comment by Psychlist1972** [comment]
Ok. This one has a lot more dependencies than the previous ones. I need to see what's pulling them all in. Reopening this until you confirm that the `Windows.Devices.Midi2-Updated.zip` I just put in the release works for you. Thanks again.

**Comment by Psychlist1972** [comment]
For convenience, I've added two other packages to the release.
1. cppwinrt.exe version used for this build, plus instructions
2. Package with full set of headers for cppwinrt.exe generated against the latest Windows SDK version 10.0.22621.0

**Comment by jcelerier** [comment]
thanks a lot, all this sounds like it will really simplify things !  checking asap

**Comment by jcelerier** [comment]
yay, it allows me to move forward, thanks a lot!

**Comment by Psychlist1972** [comment]
Very cool! Glad that got you going. Congratulations on libremidi :)
