### ISSUE TITLE
[BUG] Single MIDI streaming interface shows up as multiple UMP endpoints.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#305]
**Describe the bug**
Roland OCTA-CAPTURE is a vendor specific USB MIDI 1.0 device, and it has two MIDI ports named "MIDI" and "CTRL".
The device consists of two MIDI port objects as below:
![image](https://github.com/microsoft/MIDI/assets/114042371/4f27343d-61bb-4f83-adbd-dcd3126e4421)

If I enumerate UMP endpoints, two "OCTA-CAPTURE" endpoints show up.
![image](https://github.com/microsoft/MIDI/assets/114042371/ac327701-4c56-4c69-9d5e-86a1c4270a3d)

However, since the device only has a single USB MIDI stream, it should be configured as a single UMP endpoint.

And also, if I run the "send-message" command on both UMP endpoints, no message was sent out to the USB stream.

This issue may occur not only on the OCTA-CAPTURE but also other devices which have similar topology.

**To Reproduce**
1. Attach the Roland OCTA-CAPTURE to the PC and wait for a while for the driver to be installed automatically.
2. With any MIDI 1.0 app, make sure that two MIDI ports named "MIDI" and "CTRL" exist.
3. Run 'midi enum ump' to enumerate UMP endpoints for the OCTA-CAPTURE.
4. Run 'midi endpoint send-message' on any of OCTA-CAPTURE's UMP endpoint.

**Expected behavior**
Only a single UMP endpoint shows up for OCTA-CAPTURE.
Sent messages are sent out to the USB stream.

**Screenshots**
[Device Properties.zip](https://github.com/microsoft/MIDI/files/14832947/Device.Properties.zip)
Attached file contains two files:
- Devices on MIDI settings.png: Screenshot of the MIDI settings app.
- Endpoint Properties.txt: Output of 'midi endpoint properties' command.

**Installer Name or Version**
 - Service: Windows.MIDI.Services.Developer.Preview.5.x64.1.0.24066.2126.exe
 - Driver: Updated_USBMIDI2_10.0.1.4.zip

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Build: 26090.1

**Device information, if this is with an external MIDI device:**
 - Device: Roland OCTA-CAPTURE
 - Driver: [OCTA-CAPTURE driver ver.1.5.3 for Windows 10/11]( https://www.roland.com/global/support/by_product/octa-capture/updates_drivers/a3a79a1c-d17d-475c-b29c-03bc4f075818/)

**Comment by m-komo** [comment]
> And also, if I run the "send-message" command on both UMP endpoints, no message was sent out to the USB stream.

This was my misunderstanding.
Messages were sent out to the USB stream correctly.

So now, the question is why two UMP endpoints show up? Is this related to the [Issue#184](https://github.com/microsoft/MIDI/issues/184)?

**Comment by Psychlist1972** [comment]
@m-komo I assume this shows up as two separate devices under "Sound, video and game controllers" in Device Manager? If so, then it has two separate MIDI streaming interfaces, and we'll see it as two distinct MIDI devices.  (Our naming for those devices is not currently correct. I'll need to see the descriptors for this device to see where the names are set).

What I believe is happening here is the device exposes two separate MIDI interfaces, and each has separate pins (pin 0 and 1 from each). It really depends on what the driver is surfacing to us, though.

I don't have one of these devices. Do you have any info on the descriptors it exposes?

**Comment by m-komo** [comment]
@Psychlist1972 

The device has a single MIDI interface with two endpoints for input and output and it shows up as a single device under "Sound, video and game controllers" in Device Manager.
As you can see in the screenshot of KSStudio, our driver instantiates two port objects to name each port.

I noticed we can reproduce this with the A-88mkII running in the vendor specific mode.

![image](https://github.com/microsoft/MIDI/assets/114042371/db2a249e-ca4f-4c5f-87fd-184b32fc86ea)

Could you try with it?

You can download A-88 mkII driver for Windows from below:
https://www.roland.com/global/support/by_product/a-88mk2/updates_drivers/0de54026-b31b-45ae-9d2c-975247eb01e4/

Please see Owners Manuals to switch the A-88 mkII to the vendor specific mode.
https://www.roland.com/global/products/a-88mk2/support/

**Comment by Psychlist1972** [comment]
I'll try this with the A-88mk2. However, Gary explained the logic here. If there are multiple filters, it will show up as multiple endpoints. That's how it works with MIDI 1.0 and the classic APIs.

We can consider different logic here, but it wasn't in our plans to date.

Going to leave this one open not because it's actually a bug (it works today like it did in the past), but it's a behavioral change we can consider implementing.

**Comment by m-komo** [comment]
Implementing multiple filters is common way to name each MIDI port.
In fact, there are same cases with several third-party vendor products.

As you pointed, it should work fine with applications which use the classic APIs (MIDI 1.0 APIs).
However, there are some concerns when using the MIDI 2.0 APIs. 

- Since all filters are configured as UMP endpoints with the same name, it is impossible to distinguish which MIDI port each UMP endpoint connects to.

- It is not possible to sort-out and manage messages by group number when playing and recording UMP messages to/from multiple UMP endpoints.

Followings are possible examples of what happens if a single MIDI 1.0 streaming interface is divided to multiple UMP endpoints:

- It is not possible to play back a data which contains UMP messages with multiple group numbers, such as a MIDI Clip file, on a single UMP endpoint.

- When recording UMP messages from multiple UMP endpoints, all UMP messages are received with a same group number (group index 0). Recorded UMP messages cannot be merged and saved without re-setting group number.

These will be an obstacle and a limitation to using existing MIDI 1.0 devices from applications that use MIDI 2.0 APIs.
I don't know how to do it, but we need to find some kind of solution.

**Comment by dmiura** [comment]
Yamaha also check it with our product Montage(not Montage M) which use vendor USB MIDI 1.0 driver.
Montage has 3 ports.
Vendor Driver: https://usa.yamaha.com/support/updates/yamaha_steinberg_usb_driver_for_win.html

Result: midi.exe shows 3 UMP Endpoint with same name.
![Unknown](https://github.com/microsoft/MIDI/assets/8167750/bd8a0ca4-1bef-4aed-a012-2c7856d2abaf)

Also we checked using ksstudio, it shows three separated name, like MONTAGE-1, MONTAGE-2 and MONTAGE-3.
<img width="305" alt="Unknown" src="https://github.com/microsoft/MIDI/assets/8167750/b650d163-0e15-4c04-b080-f289f7ea757f">

**Comment by Psychlist1972** [comment]
Naming is not yet finalized because Gary and Julia are re-doing the MIDI 1.0 enumeration code (main issue right now is devices only show up if they have a single in and a single out). But it's good to know that you use the filters for naming, instead of iJack. So many ways to provide names for devices, unfortunately.

**Comment by Psychlist1972** [comment]
I'm bringing the filter thing back to Gary and Julia for consideration. I don't know if this can work within the Windows USB structure, and what will happen if other devices use filters in other ways, but they will know.

**Comment by MusicMaker** [comment]
@m-komo do you have  a USB device descriptor dump ? Would like to experiment with that.

**Comment by m-komo** [comment]
Hi @MusicMaker,
I have attached the descriptor dump file.
Since it is the vendor specific class, it may not be helpful for you.
[A-88MK2.txt](https://github.com/microsoft/MIDI/files/14985176/A-88MK2.txt)

**Comment by MusicMaker** [comment]
Question, Shouldn't vendor specific devices still use their legacy driver and then be handled by the service instead of the class compliant MIDI 2.0 driver ?

**Comment by garydan42** [comment]
Pnp will always pick the most specific driver available, most specific meaning an inf that specifies the most complete matching hardware id. The class driver doesn’t specify a hardware id, just a class. This means that a vendor provided driver will always be chosen over the class driver.

Overriding this behavior is impractical. The pnp stack will always revert to the vendor driver after an OS update or whenever there’s an updated vendor driver published, so any modifications done by the user or service to change the pnp behavior will not reliably persist.

Adding the hardware ids to the class driver will also not work because the creation date for inbox drivers, including class drivers, is set to the 1980’s, intentionally, so that all vendor drivers will look newer. This way vendor drivers are favored in the event an inbox driver specifies a hardware id.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Psychlist1972** [comment]
DP8 now shows a single physical device with multiple KS filters/endpoints as a single device when using vendor or class MIDI 1.0 drivers.
