### ISSUE TITLE
Preview 5 sample folder projects won't build

### ISSUE THREAD

**Issue by MusicMaker** [microsoft/MIDI#308]
**Issue**
Sample projects won't build when using Visual Studio 2022.

**How to reproduce**
Install Visual Studio  2022 with SDK's
Open nuget package manager
Add the path where the nuget package is located
Add the reference for MIDI2 to the project

**Expected behavior**
Open the project.sln file in Visual studio 
Add the nuget package for MIDI 2.0 Preview 5
Build 
No Errors

**Cause***
Sample projects for git (now preview 5) visual studio project files show:
`
  <Import Project="packages\Windows.Devices.Midi2.1.0.0-preview.3-0129\build\native\Windows.Devices.Midi2.props" Condition="Exists('packages\Windows.Devices.Midi2.1.0.0-preview.3-0129\build\native\Windows.Devices.Midi2.props')" />
`

**Solution** (Edited)

1.  Add the path to the nuget for preview 5 in nuget package manager 
         (the nuget package is in the project folder or download it separately and place in a folder)
2. Add the reference for  midi2 preview 5 in mage packages for project
3. Save project and close Visual studio
4. Delete ALL references to preview 3 from the project file (there are 3 areas to delete)
     Why manual ? 
        a. Somehow VS "uninstall" button does not work  to remove the preview 3 reference in the package manager
        b. Somehow VS does not delete old references in project files even they are removed
5. Open VS
6. Update main.c with code as below by [Psychlist1972](https://github.com/Psychlist1972)
7. Build the project

**Comment by Psychlist1972** [comment]
Thanks.

I assume this is the `api-watch-endpoints` sample you mentioned on Discord. If so, the event handler signatures changed per the release notes (they each take proper `args` classes as parameters now), but I missed updating this sample for Preview 5.

```cpp
    auto OnWatcherStopped = [&](MidiEndpointDeviceWatcher const& /*sender*/, foundation::IInspectable const& /*args*/)
        {
            std::cout << std::endl;
            std::cout << "Watcher stopped." << std::endl;
        };

    auto OnWatcherEnumerationCompleted = [&](MidiEndpointDeviceWatcher const& /*sender*/, foundation::IInspectable const& args)
        {
            std::cout << std::endl;
            std::cout << "Initial enumeration completed." << std::endl;
        };

    auto OnWatcherDeviceRemoved = [&](MidiEndpointDeviceWatcher const& /*sender*/, MidiEndpointDeviceInformationRemovedEventArgs const& args)
        {
            std::cout << std::endl;
            std::cout << "Removed: " << winrt::to_string(args.Id()) << std::endl;
        };

    auto OnWatcherDeviceUpdated = [&](MidiEndpointDeviceWatcher const& /*sender*/, MidiEndpointDeviceInformationUpdatedEventArgs const& args)
        {
            std::cout << std::endl;
            std::cout << "Updated: " << winrt::to_string(args.Id()) << std::endl;

            // Show how to use the various data update flags here

            if (args.UpdatedName())                     std::cout << "- Name" << std::endl;
            if (args.UpdatedUserMetadata())             std::cout << "- User Metadata" << std::endl;
            if (args.UpdatedEndpointInformation())      std::cout << "- Endpoint Information" << std::endl;
            if (args.UpdatedStreamConfiguration())      std::cout << "- Stream Configuration" << std::endl;
            if (args.UpdatedFunctionBlocks())           std::cout << "- Function Blocks" << std::endl;
            if (args.UpdatedDeviceIdentity())           std::cout << "- Device Identity" << std::endl;
            if (args.UpdatedAdditionalCapabilities())   std::cout << "- Additional Capabilities" << std::endl;

        };

    auto OnWatcherDeviceAdded = [&](MidiEndpointDeviceWatcher const& /*sender*/, MidiEndpointDeviceInformationAddedEventArgs const& args)
        {
            std::cout << std::endl;
            std::cout << "Added  : " << winrt::to_string(args.AddedDevice().Name()) << std::endl;
            std::cout << "         " << winrt::to_string(args.AddedDevice().Id()) << std::endl ;
        };

```

**Comment by Psychlist1972** [comment]
Did you mean to have something in this part of the report?

![image](https://github.com/microsoft/MIDI/assets/1421146/f6b2e0c9-dd6d-42e4-b922-1067edeb4d55)

**Comment by Psychlist1972** [comment]
Thanks for catching this one. Will be fixed in next PR to main.

**Comment by MusicMaker** [comment]
![image](https://github.com/microsoft/MIDI/assets/7860894/4ebbac28-c8ff-4906-a70d-ee05f6f16418)
Github hid the content. Fixed now.

**Comment by Psychlist1972** [comment]
Completed. Samples are updated in main. Everything will be synchronized with the next dev preview.
