### ISSUE TITLE
[BUG] UMP packet split across USB transaction is corrupted.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#312]
**Describe the bug**
If a USB MIDI 2.0 device sends a UMP message consisting of multiple 32-bits word across multiple USB transactions, received UMP messages are corrupted.

**To Reproduce**
1. Update ProtoZOA with the attached firmware ([ZOA-ExceedMPS.uf2.zip](https://github.com/microsoft/MIDI/files/15008835/ZOA-ExceedMPS.uf2.zip)).
2. Update the driver to the USB MIDI 2.0 driver (UsbMidi2.sys).
3. Open midi.exe in two windows.
4. From one, monitor "ZOA-ExceedMPS".
5. From the other, send NOOP (0x00000000) to "ZOA-ExceedMPS".
	'midi endpoint send-message 0x00000000'

With this firmware, the device sends following UMP packets when the device receives NOOP (0x00000000).
```
0x10F80000
0x40900100 0x00010000
0x40900200 0x00020000
0x40900300 0x00030000
0x40900400 0x00040000
0x40900500 0x00050000
0x40900600 0x00060000
0x40900700 0x00070000
0x510d0001 0x02030405 0x06070809 0x0a0b0c0d
0x40900800 0x00080000
```
Since the max packet size of the device endpoint is 64 bytes, MT5 message is split into two USB transaction.
![image](https://github.com/microsoft/MIDI/assets/114042371/58a79e7e-1018-4390-a29f-d93ce7cfb51a)

As a result, received messages are corrupted like as below:
![Received Messages](https://github.com/microsoft/MIDI/assets/114042371/dc2f6cd9-5835-4617-bd95-44f91b138039)

**Expected behavior**
All sent messages are displayed on the monitor as is.

**Log files**
I have attached a USB transaction log file.
[ExceedMPS.usb.zip](https://github.com/microsoft/MIDI/files/15008843/ExceedMPS.usb.zip)

**Installer Name or Version**
 - Service: Windows.MIDI.Services.Developer.Preview.5.x64.1.0.24066.2126.exe
 - Driver: Updated_USBMIDI2_10.0.1.4.zip

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Build: 26100.1

**Device information, if this is with an external MIDI device:**
 - Device: ProtoZOA w/attached firmware([ZOA-ExceedMPS.uf2.zip](https://github.com/microsoft/MIDI/files/15008835/ZOA-ExceedMPS.uf2.zip)).

**Comment by AmeNote-Michael** [comment]
Driver does not currently properly handle a UMP message across multiple USB packets. Resolution is to not advance the received Index until ump Packet is complete. To be implemented and tested for next attestation release.

**Comment by AmeNote-Michael** [comment]
This issue still needs regression testing as of Test Signed driver.

**Comment by AmeNote-Michael** [comment]
Expected output from test program. Thank you @m-komo for supplying the ProtoZOA load, made validation simpler.

![Screenshot 2024-07-08 195450](https://github.com/microsoft/MIDI/assets/90074657/715bb977-bcbf-4a9b-ae9e-1c7f344fe2fc)

**Comment by m-komo** [comment]
I have confirmed that the issue has been solved.
- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
- OS: Windows 11 24H2 (OS Build 26100.1150)
