### ISSUE TITLE
[BUG] MT4 to USB MIDI 1.0 message conversion issue.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#328]
**Describe the bug**
MT4 messages sent to USB MIDI 1.0 devices that work with the USB MIDI 2.0 driver have several message conversion issues. 

1) Note On/Off velocity value is always zero.
![image](https://github.com/microsoft/MIDI/assets/114042371/c395f9d6-f5f0-4d6e-a8f3-c2a3ce739f8d)

2) RPN/NRPN Data Entry value converted to 14bits value is incorrect.
![image](https://github.com/microsoft/MIDI/assets/114042371/247e624a-158b-4255-8de2-3629c5c35e47)

**To Reproduce**
1. Set the Roland UM-ONE mk2 to class-compliant mode and short INPUPT and OUTPUT to loop back messages.
2. Attach the UM-ONE to PC.
3. Update the driver to the USB MIDI 2.0 driver (UsbMidi2.sys).
4. Open midi.exe in two windows.
5. From one, monitor UM-ONE.
6. From the other, send following messages to UM-ONE.
> ```
> 0x40804000 0x02000000
> 0x40904000 0xFFFF0000
> 0x40201357 0x55555555
> 0x40302468 0xCDCDCDCD
> ```
7. Verify received messages.

**Installer Name or Version**
 - Service: **[interim preview build]** Windows MIDI Services Developer Preview 6 1.0.24110.1753-x64.exe
 - Driver: Updated_USBMIDI2_10.0.1.4.zip (DP5)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OS Build: 26200.5001

**Device information, if this is with an external MIDI device:**
 - Device: Roland UM-ONE mk2 (Any USB MIDI 1.0 device)

**Comment by Psychlist1972** [comment]
Thank you for this test and report.

**Comment by Psychlist1972** [comment]
On this one, the MIDI 1.0 velocity will need to be 7 bits, not 8.

`09 90 40 FF` should actually be `09 90 40 7F`

In either case, `00` is not correct, but it shouldn't be `FF`

**Comment by m-komo** [comment]
> In either case, 00 is not correct, but it shouldn't be FF

Yes, it was my miswriting.
Thank you.

**Comment by Psychlist1972** [comment]
Found a casting bug which caused the FFFF to become zero. Thanks.

**Comment by Psychlist1972** [comment]
Also: Velocity 0 for Note off (0x8) is valid. It's only the Note On message (0x9) where a 0 velocity in MIDI 2.0 protocol is translated to 1 when in MIDI 1.0 protocol.

**Comment by m-komo** [comment]
Hmm, there is still something wrong with the translator.

First, I would like to make sure the expected result.
Following is the expected result based on my understanding.
![image](https://github.com/user-attachments/assets/1b1ef494-5edd-4792-8b95-8eec9a0f75bb)

Is this right?

If so, Note ON velocity and Data Entry seem not translated correctly.
![image](https://github.com/user-attachments/assets/ca4b410e-cb54-4920-b1a4-36183e1de5e6)

I sent [Test328.txt](https://github.com/user-attachments/files/16280206/Test328.txt) to verify.

- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
- OS: Windows 11 24H2 (OS Build 26100.1150)

**Comment by Psychlist1972** [comment]
Looking into this.

**Comment by Psychlist1972** [comment]
Verified this works with DP7.

Results sending Test328.txt to a MIDI 1.0 hardware loopback

![image](https://github.com/user-attachments/assets/697d3bea-772f-4642-b222-d0f016673818)

**Comment by m-komo** [comment]
> Edit: Actually, that's the down-scaling of the 0x0200 velocity in the second MT4 word of the note off message, which also happens to be the example in the spec. "MIDI Velocity = 0x01: translates to 0x0200"

My apologies, the table I shared should be as below:

![image](https://github.com/user-attachments/assets/e26b86ba-65cb-44a6-9d07-dcbf64b19f3f)
