### ISSUE TITLE
[BUG] Windows MIDI Service virtual device doesn't appear in 3rd Party Software

### ISSUE THREAD

**Issue by simonbosley** [microsoft/MIDI#343]
**Describe the bug**
I've created a .Net Console App that creates a Windows MIDI Service virtual device. It periodically sends NoteOn and NoteOff messages (with successful return codes).

I can see it is reported in the Windows MIDI Service Console tool:

![image](https://github.com/microsoft/MIDI/assets/1934221/6cde7ab0-0158-419f-ad58-f0fef4b29c55)

When I open 3rd Party software, such as the Reaper DAW for example, the Virtual MIDI Device does not appear (note that the SSL V-MIDI ports are from our current software for UF8 that are created by Tobias Ericsson VirtualMIDI, not what I'm creating with this Windows MIDI Service test):

![image](https://github.com/microsoft/MIDI/assets/1934221/77a40c7e-e497-43f3-b363-f03f6ebc13e5)

**To Reproduce**

1. Run a Console App that creates a Windows MIDI Service Virtual Device.
2. Check the Windows MIDI Service Console to check device is created correctly.
3. Check 3rd party software to see if the Virtual MIDI Device appears.

**Expected behavior**
I expected the Windows MIDI Service Virtual Device to appear in the list MIDI devices in 3rd party software.

**Installer Name or Version**
Windows.MIDI.Services.Developer.Preview.5.x64.1.0.24066.2126.exe

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise 23H2
 - OS Build: 22631.3593

**Application Information**
DAW: Reaper v7.15/win64

**Comment by Psychlist1972** [comment]
This is a known limitation until Windows MIDI Services is in-box in Windows (insider preview or retail) and the WinMM shim is in-place. The older APIs do not yet talk to the service.

Related to #229, #49, #34

**Comment by Psychlist1972** [comment]
BTW, Congrats on creating the virtual device!

**Comment by simonbosley** [comment]
Thanks, it was great to see something up and running for the first time in the new Windows MIDI Service. We can now continue to prepare something for a future release when it goes in-box.

Thanks for all the help!
