### ISSUE TITLE
[BUG] USB OUT packet is padded with NOOP up to the max packet size.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#357]
**Describe the bug**
Even if a single UMP is sent, all USB OUT packets are padded with NOOP up to the maximum packet size. 

**To Reproduce**
1. Attach any USB MIDI 2.0 device to PC.
2. Update the driver to the USB MIDI 2.0 driver (UsbMidi2.sys).
3. Run 'midi.exe ep send 0x20901234'
4. Observe USB transaction.

**Expected behavior**
USB OUT packet only contains the single UMP sent.
USB OUT packet should not be padded with NOOP.

**Screenshots**
I have attached a [Captured USB log.usb.zip](https://github.com/user-attachments/files/16173276/Captured.USB.log.usb.zip)

![image](https://github.com/microsoft/MIDI/assets/114042371/1a58aefe-c694-4b15-a7f6-f8fec0d6d99c)

![image](https://github.com/microsoft/MIDI/assets/114042371/13d9d2fb-cf58-4844-8030-becafe88d4c2)

**Installer Name or Version**
- Service: [interim preview build] Windows MIDI Services Developer Preview 6 1.0.24110.1753-x64.exe
- Driver: [interim preview build] USBMidi2x86-240708-10.0.10011.16384-TESTSIGNED.zip

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2
 - OS Build:  26100.1150

**Device information, if this is with an external MIDI device:**
 - Any USB MIDI 2.0 device compatible with the USB MIDI 2.0 driver(USBMidi2.sys)

**Comment by Psychlist1972** [comment]
Assigning to @AmeNote-Michael because I believe this is related to the multiple message per packet handling in the USB MIDI 2.0 driver.

**Comment by AmeNote-Michael** [comment]
@m-komo this is resolved in next released driver.

**Comment by AmeNote-Michael** [comment]
For reference, here is USB capture log of sending a single UMP Packet and receiving same packet in loopback. Note no padding.

<img width="856" alt="image" src="https://github.com/user-attachments/assets/e6ef1378-c8d4-45c9-b076-3c49ffc93f14">

**Comment by m-komo** [comment]
I confirmed that the issue has been solved.
- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
