### ISSUE TITLE
[BUG]Older MIDI 1.0 class drivers will drop some SysEx from USB-MIDI 1.0 devices

### ISSUE THREAD

**Issue by masahirokakishita** [microsoft/MIDI#372]
**Describe the bug**
Older MIDI 1.0 class drivers will drop some SysEx from USB-MIDI 1.0 devices

**To Reproduce**
1. Install the enclosed SevenColor4,uf2. This is a USB-MIDI 1.0 device. This is a USB-MIDI 1.0 device.

[SevenColor4.uf2.zip](https://github.com/user-attachments/files/16342693/SevenColor4.uf2.zip)

3. Open a console
4. Monitor UMP message

> midi endpoint monitor -verbose

5. Touch the touchpad "1" of ProtoZoA. ProtoZoA send following messages.

04 f0 0b 0c
04 0d 0e 0f
04 10 11 12
07 13 14 f7

6.  One MT3 message is displayed by the console.

30160B0C 0D0E0F10

**Expected behavior**

Two MT3 message is needed. Because there are ten bytes SysEx.

30260B0C 0D0E0F10
30341112 13140000

**Screenshots**
![image](https://github.com/user-attachments/assets/afbf29dc-529b-4c23-adaf-1e1094c3b193)

**Installer Name or Version**
dev-preview-6/Windows.MIDI.Services.App.SDK.Runtime.-.Developer.Preview.6.1.0.24194.2233-arm64.exe
dev-preview-6/Windows.MIDI.Services.Console.-.Developer.Preview.6.1.0.24194.2233-arm64.exe
dev-preview-6/Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-arm64.exe
240713-USBMidi2-Arm64-TESTSIGNED

**Desktop (please complete the following information):**
Snapdragon 3GHz Windows 11 Pro
Build 26100.ge_release.240331-1435

**Comment by Psychlist1972** [comment]
@masahirokakishita If you have the ability and desire to test this, can you tell me if you see the same dropping of messages if you send the equivalent byte data through the older WinMM or WinRT MIDI 1.0 APIs, not using Windows MIDI Services? Maybe looking at it through a tool like MIDI-OX?

I'm keen to understand if this is a problem with our old driver, or a problem with Windows MIDI Services.

**Comment by MusicMaker** [comment]
Also recommend look at Mountain MIDI tools, it seems to handle sysex a bit better but not perfect.  Al of them including Pocket MIDI and OX have issues with sysex in some situations (i.e realtime, see the other bug posted today).

**Comment by masahirokakishita** [comment]
I used Pocket MIDI. And It’s no problem.

![image](https://github.com/user-attachments/assets/093b1d9e-6348-4d6b-b1cc-7e3d31c8caf5)

**Comment by masahirokakishita** [comment]
I have a mistake, the expected behavior is as below.

30160B0C 0D0E0F10
30341112 13140000

**Comment by m-komo** [comment]
I was able to reproduce this issue with the UM-ONE (Class Compliant Mode).

Received following messages from the UM-ONE's MIDI INPUT:
![image](https://github.com/user-attachments/assets/1f375892-5b69-4498-9314-a0af1a0b7020)

midi.exe ep monitor shows:
![image](https://github.com/user-attachments/assets/d132cd4c-2d24-4398-a6fc-01d5b84773fb)

Monitor with the PocketMIDI:
![image](https://github.com/user-attachments/assets/1545eb96-c17e-470d-bb6f-233b7204e750)

**Comment by Psychlist1972** [comment]
> I was able to reproduce this issue with the UM-ONE (Class Compliant Mode).
> 
> Received following messages from the UM-ONE's MIDI INPUT: ![image](https://private-user-images.githubusercontent.com/114042371/353388189-1f375892-5b69-4498-9314-a0af1a0b7020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDQxMzMsIm5iZiI6MTcyMjM0MzgzMywicGF0aCI6Ii8xMTQwNDIzNzEvMzUzMzg4MTg5LTFmMzc1ODkyLTViNjktNDQ5OC05MzE0LWEwYWYxYTBiNzAyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxMjUwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGVkOGEwNWEzMTBjZjVkMGMzMmEwZWM1MzFkZmUyMGVkZGQzOTM0MzA1ZTdhZWQwNjI0MDY4MDMxODg0YmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0vXDnBZE40Khgarb4r486tIvrqxiA1pfQjVhFty5ntc)
> 
> midi.exe ep monitor shows: ![image](https://private-user-images.githubusercontent.com/114042371/353388275-d132cd4c-2d24-4398-a6fc-01d5b84773fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDQxMzMsIm5iZiI6MTcyMjM0MzgzMywicGF0aCI6Ii8xMTQwNDIzNzEvMzUzMzg4Mjc1LWQxMzJjZDRjLTJkMjQtNDM5OC1hNmZjLTAxZDViODQ3NzNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxMjUwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjA0MTNjODAyYzg2OTdlOTBmYWRlNjQwNTFjNmYxNTJlMmI5MGQyMmFmYWY1MDFiNDQ5ZDAxMTFmMWRjODVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7TvmSxC-YPoXXllf37CaV0r2bwyOKKE6Cz62mbCVo-k)
> 
> Monitor with the PocketMIDI: ![image](https://private-user-images.githubusercontent.com/114042371/353388937-1545eb96-c17e-470d-bb6f-233b7204e750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDQxMzMsIm5iZiI6MTcyMjM0MzgzMywicGF0aCI6Ii8xMTQwNDIzNzEvMzUzMzg4OTM3LTE1NDVlYjk2LWMxN2UtNDcwZC1iYjZmLTIzM2I3MjA0ZTc1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxMjUwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDk3ZTdmMTIzMWI3Y2U2N2E0YzNhOTVjODNmY2M3YWI3Mzg2ZDhmZTExYTdkMjlkNzlhYjgwNDAyZTUxMDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.31blE4Pah2nlQCnNbiukL2dGBVjWa4a25Jmb2ZraXBU)
> 
> * Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
> * Driver: [interim preview build] 240719-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/19/2024,23.22.46.475)
> * OS: Windows 11 24H2 (OS Build 26100.1150)

(Note for others viewing: this isn't using the MIDI 2 / UMP interim driver. It's using the older usbaudio.sys)

**Comment by Psychlist1972** [comment]
This is likely related to the bug I just logged for libmidi2

https://github.com/midi2-dev/AM_MIDI2.0Lib/issues/23

**Comment by Psychlist1972** [comment]
Andrew is working on updates to libmidi2 which should address this.

**Comment by MusicMaker** [comment]
> I used Pocket MIDI. And It’s no problem.
> 
> ![image](https://private-user-images.githubusercontent.com/13650605/353358418-093b1d9e-6348-4d6b-b1cc-7e3d31c8caf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MjMxMTMsIm5iZiI6MTcyMjUyMjgxMywicGF0aCI6Ii8xMzY1MDYwNS8zNTMzNTg0MTgtMDkzYjFkOWUtNjM0OC00ZDZiLWIxY2MtN2UzZDMxYzhjYWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE0MzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MzVkY2E4YjFkMDVkY2UxMTFlYzgxNDM0YjUwY2MyMWQxOWRkMzdlYWJlZjMwMjNjNmJmZmUzOWI5MjY1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IRnSgjLAuJvNJ120w9V33-39cgDqhi3oujTbRfFP2Ew)

Sorry. What I meant was also inserting F8 , FA, FB, FC into the sysex either UMP to legacy.

**Comment by Psychlist1972** [comment]
Andrew has updated his libmidi2 code so this will be resolved in the next preview

**Comment by Psychlist1972** [comment]
Closed with release of DP7
