### ISSUE TITLE
[BUG] BS2UMP transform always sets group to 0 (for a MIDI 1.0 client)

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#377]
**Describe the bug**
group always set to zero 

**Expected behavior**
Group needs to match the group index for that midi 1.0 port

**Installer Name or Version**
DP6

**Comment by m-komo** [comment]
Does this case occur on a USB MIDI 1.0 device running with the USB MIDI 1.0 driver (USBAUDIO.sys)?

**Comment by Psychlist1972** [comment]
> Does this case occur on a USB MIDI 1.0 device running with the USB MIDI 1.0 driver (USBAUDIO.sys)?

Yes. This applies to MIDI 1.0 devices using a vendor or MIDI 1.0 class driver. It also applies to the older MIDI 1.0 APIs in Windows (but you cannot test that part yet)

This does not apply to anything using the UMP class driver.

**Comment by m-komo** [comment]
Probably, I don't understand this well, but I would like to share my test result.

1. Load attached [UUT_ZOA_104.zip](https://github.com/user-attachments/files/16428421/UUT_ZOA_104.zip) to the ProtoZOA.
This firmware works as a USB MIDI 1.0 device with four input and output ports, and all received messages are echo back to the host.
3. Attach the device to PC and make sure the device is running with the OS in-box USB MIDI 1.0 driver (USBAUDIO.sys).
4. Open a console and monitor the attached device.
5. Open another console and send [GrpIndexTest.txt](https://github.com/user-attachments/files/16428437/GrpIndexTest.txt)  which contains MT2 message with group index of 0-7.

Messages which have group index of 0-3 were sent to the device and other messages were dropped.
![image](https://github.com/user-attachments/assets/f98cf645-e1ad-40d6-a767-6e0368719c80)

Then all received messages were displayed on the monitor.
![image](https://github.com/user-attachments/assets/d155de75-9b33-479a-87c0-9b152a15475b)

So, it seems everything works as expected...

**Comment by Psychlist1972** [comment]
Thanks @m-komo

I just realized that this won't apply to the devices themselves, but only to the older MIDI 1.0 APIs. The devices have the incoming translation happening in the KSA abstraction for this very reason. But when a MIDI 1.0 client connects, it does not have the group # context, so neither does the translation code.

Keeping this open until others are able to test integration with the older winmm and WinRT MIDI 1.0 APIs.

**Comment by Psychlist1972** [comment]
Closing this one. #418 correctly captures the current state.
