### ISSUE TITLE
[BUG] Supporting MIDI Bytes Stream based on series of CIN=0xf in USB MIDI 1.0 devices

### ISSUE THREAD

**Issue by AmeNote-Michael** [microsoft/MIDI#378]
**Describe the bug**
The new USBMidi2.sys driver currently only handles special cases of single byte MIDI transfers like system realtime messages.

Apparently there are devices in market that use single byte transfer to send MIDI byte stream instead of converting to optimized other CIN message types - ie it could take 3 USB packet transfers to send a note on instead of 1.

**To Reproduce**
Currently do not have an example device to create this issue.

**Expected behavior**
The constructed byte stream should be converted to appropriate UMP data.

**Comment by AmeNote-Michael** [comment]
Going to review how to implement with existing architecture. Trying to avoid a large rewrite.

**Comment by AmeNote-Michael** [comment]
Option is, these type of devices must be used with old USB MIDI 1.0 driver.

**Comment by Psychlist1972** [comment]
What a crazy waste of USB resources to send one byte per transfer. Yikes.

**Comment by Psychlist1972** [comment]
> Going to review how to implement with existing architecture. Trying to avoid a large rewrite.

Don't change to support this unless we find it's a meaningful percentage of devices.  Requiring them to use the old driver is also reasonable if this isn't some majority of devices.

Do you know the make/model of any of the devices? I'll see if it's something I have around, or can get.

**Comment by AmeNote-Michael** [comment]
> Do you know the make/model of any of the devices? I'll see if it's something I have around, or can get.

I do not - just heard that they exist. Basically a lazy implementation.

Perhaps something to bring up on Wednesday, maybe someone in AMEI knows. But I was also going to look into trying to implement on ProtoZOA if it is determined we need to support.

I think it is really rare case. @AmeNote-MikeKent do you have any comment?
