### ISSUE TITLE
[BUG] Services always requests MIDI 2.0 protocol even if the endpoint has not declared MIDI 2.0 protocol compatibility

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#379]
**Describe the bug**
During protocol negotiation, the service always requests MIDI 2.0 protocol, even if the returned endpoint info from discovery shows only MIDI 1.0 compatibility.

**Expected behavior**
The service should try to negotiate MIDI 2.0 protocol only if it is supported. Otherwise, it should negotiate MIDI 1.0 protocol. 

If neither is specified, given this is a UMP endpoint, I'm of the opinion that MIDI 2.0 should be the default. Happy to listen to dissenting opinions on this.

**Comment by MusicMaker** [comment]
A dissenting opinion :-)
![image](https://github.com/user-attachments/assets/f1ad4518-f200-4c7b-a2ed-223ff1994398)

**Comment by Psychlist1972** [comment]
Closed with release of DP7
