### ISSUE TITLE
[BUG] Windows cannot load the drivers required for this device.(Code 31)

### ISSUE THREAD

**Issue by masahirokakishita** [microsoft/MIDI#398]
I am posting this in the hope that it will give you some hints on how to solve the problem.

Windows 11 Insider Preview 27695 fails to install on my PC.

Windows 11 Insider Preview 27695.1000 (rs_prerelease)
Install Error - 0xc1900101

Therefore, when I try to update to the MIDI 2.0 driver, I get the following error.

![error](https://github.com/user-attachments/assets/6eb30625-ff6e-4722-80f8-f2acd531ed74)

My PC is old, with a Core i5 9600k CPU and an H310 chipset,
I updated Windows 11 from Windows 10.
Windows 11 Home 10.0.22635 build 22635

Is there any way to fix this?

**Comment by masahirokakishita** [comment]
Thank you for your suggestion. But it seems tough for me to read the install log file. I will reinstall it from scratch.

**Comment by Psychlist1972** [comment]
From your other reported bug, I assume this has been fixed, @masahirokakishita ?

**Comment by masahirokakishita** [comment]
Yes, please close this issue.
