### ISSUE TITLE
[BUG] The updated-cpp-samples-dp6 programs don't work

### ISSUE THREAD

**Issue by masahirokakishita** [microsoft/MIDI#415]
The sample programs in the updated-cpp-samples-dp6 folder, for example client-basics-cpp, don't work in my environment.
The following line becomes fail.

```
auto session = MidiSession::Create(L"Loopback Sample Session");
```

This line jumps to the exception handler in base.h.

```
if (result == impl::error_class_not_registered)
{
    throw hresult_class_not_registered(take_ownership_from_abi WINRT_IMPL_SOURCE_LOCATION_FORWARD);
}
```

My environment,
Windows 11 Pro Insider Preview 27729.rs_prerelease.241011-1428
Windows.MIDI.Services.App.SDK.Runtime.-.Developer.Preview.6.1.0.24194.2233-x64
Windows.MIDI.Services.Console.-.Developer.Preview.6.1.0.24194.2233-x64
Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64
Windows SDK 10.0.20348.0
Visual Studio 2022

**Comment by MusicMaker** [comment]
This ? https://discord.com/channels/980245825202552942/1119712926136270959

**Comment by Psychlist1972** [comment]
This will be less troublesome in DP7, but you will still need to ensure the implementation DLLs are in the folder with your .exe. The .targets file is supposed to ensure this, but I've noticed that it does not always copy them.

**Comment by Psychlist1972** [comment]
Closed with release of DP7
