### ISSUE TITLE
[Feature] A solution to check if eventRevokeToken is valid.  (API)

### ISSUE THREAD

**Issue by MusicMaker** [microsoft/MIDI#431]
**Problem**

Not able to  check if eventRevokeToken is valid upon creation.

auto eventRevokeToken = receiveEndpoint.MessageReceived(MessageReceivedHandler);

The token  has a property. value which is unin64_t. It not defined how to check it is valid or not.

**Describe the solution you'd like**

Make the value  negative  if invalid.

**Comment by Psychlist1972** [comment]
The  `winrt::event_token` has a boolean operator overload, so just `if (token) { ... revoke code ... }` will do it.

**Comment by MusicMaker** [comment]
Confirmed. works (DP7), if (!token) works too. :-)
