### ISSUE TITLE
Service does not process function block info notifications from a MIDI 2.0 UMP USB device

### ISSUE THREAD

**Issue by MusicMaker** [microsoft/MIDI#441]
**Describe the bug**
When a device sends a Function Block Notification request, after the initial enumeration process after insertion of the device, the Windows MIDI service does not seems to process it. This case is when non-static function blocks are used.

**To Reproduce**
 
1. Send a response upon enumeration after insertion of the device: 

F0118633 08020101 00000000 00000000 Stream (0F) Function Block Info Notification Complete, Block 6 , Active Yes, UI Hint 03h, m1.0 00h, Direction 03h, First Group 8, Number of Groups 2, MIDI-CI Version 0001h, Sysex8_Streams 1
 
2. After some time send an info notification from the device to the host: 

F0118633 08050001 00000000 00000000 Stream (0F) Function Block Info Notification Complete, Block 6 , Active Yes, UI Hint 03h, m1.0 00h, Direction 03h, First Group 8, Number of Groups 5, MIDI-CI Version 0000h, Sysex8_Streams 1

3. check midi.exe  ep props. The groups did not change

**Expected behavior**

According to page 37 of UMP 1.1.1. a device can send a info notification. Groups should be increased after receiving the info notification

**Installer Name or Version**

DP7 , Driver: 10.0.1.7

**Desktop**
 - OS:  Windows 11  Pro Canary, Insider preview:   27754.1000
 
**Device information, if this is with an external MIDI device:**
Yes, custom

**Application Information**
N/A

**Additional context**
B.T.W the UMP 1.1.1 specification does not define an "ACK" or "NACK". As such the device actually does not know if the service really has processed the requests. An option could be for a device to send a info request to the host to get the function block data, but it appears this UMP message is only defined as host to  device....

**Comment by MusicMaker** [comment]
Strangely after a reboot of Windows 11 this now worked.

**Comment by Psychlist1972** [comment]
As requested.
