### ISSUE TITLE
[BUG] "Static Function Blocks" displayed in midi.exe

### ISSUE THREAD

**Issue by tosugawara** [microsoft/MIDI#450]
**Describe the bug**
In `midi ep properties`,  "Static Function Blocks" seems to be different from the Endpoint Info Notification message.

**To Reproduce**
1. Set a custom USB MIDI 2.0 (UMP 1.1) device to PC.
2. Update the MIDI driver to the USB MIDI 2.0 driver (UsbMidi2.sys).
3. `midi ep request endpoint-info` to the device and monitor reply from it : `midi ep monitor`. Endpoint Info Notification message from the device is confirmed, and the flag of "Static Function Blocks" in this message is True (the MSB of "81" byte).![Image](https://github.com/user-attachments/assets/dbd06f5e-14ea-42cc-901b-80f41c97bd56)
3. Execute `midi ep properties` to the device,  "Static Function Blocks" is displayed as "False" here.
![Image](https://github.com/user-attachments/assets/f0fb265b-4c88-4595-807b-055d28ffdea2)

**Expected behavior**
The result in endpoint properties is "True".

**Installer Name or Version**
Windows.MIDI.Services.In-Box.Service.-.1.0.1-preview.7.24305.1438-x64.exe
USB MIDI 2.0 class driver (USBMIDI2_10.0.1.7.x64.zip)

**Desktop (please complete the following information):**
OS: Windows 11 24H2 build 26120.2415 (Insider Dev channel)

**Device information, if this is with an external MIDI device:**
custom one.

**Application Information**

**Additional context**
I tried this operation after connecting the device, so problems may be in processes of my custom device at initial Endpoint Discovery.

**Comment by Psychlist1972** [comment]
Thanks.

Did this device participate in initial discovery and declare static or dynamic function blocks when first plugged in? It would be good to know if this differs from the original value (which is not allowed).

**Comment by Psychlist1972** [comment]
Thanks. Fixed for DP8. It was a bug in the SDK

![Image](https://github.com/user-attachments/assets/5a2dc9a0-59af-4bff-be01-8ac4d8e00782)

**Comment by tosugawara** [comment]
> Did this device participate in initial discovery and declare static or dynamic function blocks when first plugged in? It would be good to know if this differs from the original value (which is not allowed).

Yes it did, and it declared static (this means "True") as initial value.

> Thanks. Fixed for DP8. It was a bug in the SDK

Thanks, I understand.

**Comment by Psychlist1972** [comment]
In DP8
