### ISSUE TITLE
Create USB MIDI 2.0 Class Driver support for MIDI 1.0 devices (including byte stream translation)

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#47]
Essential for giving the API and service access to MIDI 1.0 devices represented as UMP.

**Comment by AmeNote-Michael** [comment]
Creation of Group Terminal Blocks for USB MIDI 1.0 completes the support of USB MIDI 1.0 devices as UMP. This was completed with pull request https://github.com/microsoft/MIDI/pull/159
