### ISSUE TITLE
Create PnP + Windows.Devices.Enumeration support, including USB Group Terminal Blocks for USB MIDI Devices

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#51]

**Comment by AmeNote-Michael** [comment]
Group Terminal Blocks for both USB MIDI 2.0 and creation for USB MIDI 1.0 is complete as of https://github.com/microsoft/MIDI/pull/159. This is now in testing and debug from driver point of view.

**Comment by Psychlist1972** [comment]
I've tested this with USB MIDI 2.0 and USB MIDI 1.0 devices and haven't had any problems. Group Terminal blocks are coming through in both cases as expected. Closing as complete/fixed.
