### ISSUE TITLE
Create MIDI 2.0 multi-client support

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/MIDI#62]
Ensure support in MIDI 2.0 / UMP API for MIDI 1.0 and MIDI 2.0 devices. Out-of-scope for this task is multi-client support for WinMM and older WinRT APIs.

**Comment by Bremmers** [comment]
Not sure what "MIDI 2.0" means here, so I'm mentioning this just to make sure it's OK:

Assume an existing MIDI (byte stream) device that provides a sound module and a DIN connector which is output. Currently they appear as two MIDI ports. An app can use them independently.

The MIDI Services turn this into a single endpoint which has two active groups. Apps should be able to use these groups independently just like they could use the two ports independently. This means MidiSession.ConnectToEndpoint will be called twice.

**Comment by Psychlist1972** [comment]
I've updated the description to be more clear. This is multi-client support in new API (multiple apps opening connections to the same MIDI Endpoint). Multi-client for the older WinMM and WinRT APIs is planned, but not for the initial release. During that period when multi-client has not been back-ported to WinMM/WinRT, opening a device there that is already connected through the MIDI Services API will fail like it does today. If the MIDI Services connection is opened second, it's also expected to fail.
