### ISSUE TITLE
[BUG]'Close' function is commented out in MidiSession.idl

### ISSUE THREAD

**Issue by Bremmers** [microsoft/MIDI#96]
The 'Close' function is commented out in MidiSession.idl. Because of this the function is missing from the interface, and apps will crash.

**Comment by Psychlist1972** [comment]
Thanks for the report.

In this case, Close is a member of IClosable. Including it in the IDL would cause a duplicate function to be declared.

If you get the IClosable interface from the class, and call Close there, do you see a crash?

**Comment by Psychlist1972** [comment]
Note that the Session class isn't properly cleaning up outside of Close() right now. That will be fixed.

**Comment by Bremmers** [comment]
> If you get the IClosable interface from the class, and call Close there, do you see a crash?

That works. Thanks!
Oops, so it's not a bug ;-)

**Comment by Psychlist1972** [comment]
No worries. As I recall, Delphi has deterministic tear-down like C++, so likely won't need to call this method anyway once I put that close code in the correct place :)

**Comment by Psychlist1972** [comment]
Closed, which is appropriate :)
